### ISSUE TITLE
Spinner Utils Crashes

### ISSUE THREAD

**Issue by bendaniel10** [bendaniel10/appcommons#5]
SpinnerUtils.isEmpty crashes if the spinner doesn't contain any items.

```
                                                                java.lang.NullPointerException
                                                                    at com.bentech.android.appcommons.utils.SpinnerUtils.isEmpty(SpinnerUtils.java:26)
```

**Comment by smilecs** [comment]
Seems this issue has been open for long now is it still valid? would like to fix it. What are the processes for contributing?

**Comment by bendaniel10** [comment]
Hello, this has been resolved. Thanks for noticing this, I'll close the issue now.
